version: '3.9'
services:
  node:
    build: 
      context: ../../app
      dockerfile: Dockerfile.prod
    image: rogeriorock/node:prod
    container_name: nodefullcycle
    entrypoint: dockerize -wait tcp://db:3306 docker-entrypoint.sh node index.js
    depends_on:
      - db
    networks:
      - nodenet
  db:
    build: 
      context: ../../mysql
      dockerfile: Dockerfile
    image: rogeriorock/dbnode:prod
    container_name: db
    tty: true
    volumes:
      - ../../mysql/data_prod:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
      
  nginx:
    build: 
      context: ../../nginx
      dockerfile: Dockerfile
    image: rogeriorock/nginx:prod
    container_name: nginxfullcycle
    depends_on:
      - node
    networks:
      - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge