version: '3.9'
services:
  node:
    build: 
      context: ../../app
      dockerfile: Dockerfile.dev
    image: rogeriorock/node
    container_name: nodefullcycle
    depends_on:
      - db
    volumes:
      - ../../app:/usr/src/app
    networks:
      - nodenet
    ports:
      - "3000:3000"

  db:
    build: 
      context: ../../mysql
      dockerfile: Dockerfile
    image: rogeriorock/dbnode
    container_name: db
    tty: true
    volumes:
      - ../../mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
      
  nginx:
    build: 
      context: ../../nginx
      dockerfile: Dockerfile
    image: rogeriorock/nginx
    container_name: nginxfullcycle
    depends_on:
      - node
    networks:
      - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge